repos:
-   repo: local
    hooks:
    - id: black
      name: Auto-format files
      language: python
      entry: black
      types: [python]
-   repo: local
    hooks:
    - id: flake8
      name: Check format
      language: python
      entry: flake8
      types: [python]